// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEAoD15HV3RROetnGosNEv0WCj5B3Fjts',
    appId: '1:376555967293:web:2782cfd822ed56b2322b54',
    messagingSenderId: '376555967293',
    projectId: 'insta-db2f6',
    authDomain: 'insta-db2f6.firebaseapp.com',
    storageBucket: 'insta-db2f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0QvwmldRRpy_8Wr21agAVpYJuY9dj9QU',
    appId: '1:376555967293:android:a461a89f89b8cbc8322b54',
    messagingSenderId: '376555967293',
    projectId: 'insta-db2f6',
    storageBucket: 'insta-db2f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT3zAO7jKFZVcqhPj-qqkRMKk_chTVZJM',
    appId: '1:376555967293:ios:d09dbd077b00518f322b54',
    messagingSenderId: '376555967293',
    projectId: 'insta-db2f6',
    storageBucket: 'insta-db2f6.firebasestorage.app',
    iosBundleId: 'com.prolab.insta',
  );
}
